### ISSUE TITLE
Colocar Metodos de operações nos algoritmos

### ISSUE THREAD

**Issue by iagoluz01** [leonardoheredia/alest1-202301-Trabalho-01#1]
`

    public long getOperacoes() {
        return operacoes;
    }

    public long getTempoInicio() {
        return tempoInicio;
    }

    public long getTempoFim() {
        return tempoFim;
    }    public long getOperacoes() {
        return operacoes;
    }

    public long getTempoInicio() {
        return tempoInicio;
    }

    public long getTempoFim() {
        return tempoFim;
    }
 public long getTempoExecucao() {
        long tempoExecucao = (tempoFim - tempoInicio) / 1_000_000  ;
        return tempoExecucao;
    }
`

**Comment by leonardoheredia** [comment]
Corrigido no commit https://github.com/leonardoheredia/alest1-202301-Trabalho-01/commit/dee4cbfe9a59f36c6ee1b16678422061932a8f93
